### ISSUE TITLE
Update Sarah's bio 

### ISSUE THREAD

**Issue by sagehrke** [tis-lab/tislab.org#105]
Need to update my bio to be more relavent to my move and current tasks in TISLab.

**Comment by chrisroederucdenver** [comment]
I think you can edit that from github. Follow the[ link to your blurb ](https://github.com/tis-lab/tislab.org/blob/main/_members/sarah-gehrke.md)and look for a pen icon to edit. Switch between edit and preview to figure out [markdown syntax ](https://cloud.google.com/apigee/docs/api-platform/publish/portal/markdown-reference)if you haven't.

**Comment by tursynay** [comment]
Sarah, if you want to hop on Zoom to show, let me know

**Comment by chrisroederucdenver** [comment]
thanks. things are getting busy in CLAD land and I have nagging issue to finish in N3C.

**Comment by sagehrke** [comment]
Thank you! I still need to dedicate time to update what I want to say! But once I do, I will reach out. It's on the to-do list 😄
