### ISSUE TITLE
Update Evan's title on https://tislab.org/team/

### ISSUE THREAD

**Issue by sagehrke** [tis-lab/tislab.org#125]
Hi @evanc1648 -- please update your title on https://tislab.org/team/
Feel free to also update any other content on your team page here: https://tislab.org/members/evan-connelly.html 

Thanks! 😄

**Comment by evanc1648** [comment]
Hi @sagehrke,

I just made my changes to the title/description, profile image, and blurb; and I made a PR.

Thank you!
