### ISSUE TITLE
Remove Moni from the tislab.org Team page

### ISSUE THREAD

**Issue by sagehrke** [tis-lab/tislab.org#141]
Update the tislab.org team page to remove Moni from the list. 
Move her file to [emeriti](https://github.com/tis-lab/tislab.org/tree/main/emeriti) and remove from https://tislab.org/team/

**Comment by sagehrke** [comment]
@chrisroederucdenver Would you be able to do this for us?

**Comment by chrisroederucdenver** [comment]
done, Glass too.
