### ISSUE TITLE
Add news feed?

### ISSUE THREAD

**Issue by mellybelly** [tis-lab/tislab.org#2]
we could have the Monarch Medium blog linked for example. https://medium.com/@MonarchInit/

Also other recent news items such as:
https://www.amia.org/about-amia/leadership/spotlight-1/melissa-haendel-phd
https://ncats.nih.gov/pubs/features/cd2h

**Comment by nicolevasilevsky** [comment]
@mellybelly and @DoctorBud I am not sure the best way to set up a news feed. I could have a link on the nav bar that says "news" and links to the Monarch blog, but that wouldn't incorporate the other news sites.

Do either of you have a better idea how to set this up?

**Comment by jmcmurry** [comment]
It might be good to have it mirror tweets from monarchinit; more than that would -- imho -- not be worth the labor.

**Comment by nicolevasilevsky** [comment]
Currently I have a link to news in the nav bar that goes to the Monarch blog. Should I remove that and add a twitter feed for the Monarch twitter? That probably wouldn't appear above the fold though. Also, I don't know how to do that. :) @DoctorBud could you help?

**Comment by nicolevasilevsky** [comment]
I like how we have it set up in Monarch currently, @jmcmurry were you thinking of having something like that?

**Comment by jmcmurry** [comment]
For ease of administration, ideally the news feed should be fed from twitter. Our medium articles will be up there, as will our appearances at conferences etc.

**Comment by nicolevasilevsky** [comment]
Ok, sounds good. @jmcmurry can you clarify, is it sufficient if there is a news link in the nav bar that links to our twitter, or would you rather have a feed on the side, like in Monarch?

**Comment by jmcmurry** [comment]
Since you can't read twitter unless you're logged into twitter, it would be good if we could nevertheless have a feed. This also keeps the page looking fresh and exciting. However, in the short term, a link is fine.

**Comment by nicolevasilevsky** [comment]
Ok - I added a link to the twitter feed from the news link for now.

@DoctorBud can you help me integrate the feed into the website? I figured out the code, I just don't know where it should go.

**Comment by nicolevasilevsky** [comment]
@DoctorBud suggests that we do a news box instead of a twitter feed, something like the Su Lab's: http://sulab.org/

I like this idea personally. @jmcmurry and @mellybelly would you be in favor of this instead of a twitter feed?

**Comment by nicolevasilevsky** [comment]
Talking to @mellybelly 
going to create a 'news' page that has the Monarch blog, twitter feed, upcoming events

**Comment by jmcmurry** [comment]
It looks lovely to the eye, I agree. However, I'm worried we are biting off more than we can chew. If I'm really honest, the thought of maintaining three separate places where "news" is curated fills me with mild existential dread. Events and blogs should be tweeted so tweet feed (monarchinit only, not hashtags like previous) are the lowest and easiest bar to clear. Setting up the tislab website to consume separate streams up may indeed be trivial; I couldn't say. 
It is just the babysitting three streams in perpetuity that I'd like to not do; at least not now with so much on. @mellybelly please weigh in.

**Comment by nicolevasilevsky** [comment]
we have a news link on the nav bar that goes to the monarch twitter feed. I am calling this good enough and am closing this ticket. If we'd like to attempt to do something else, please open a new ticket.
