### ISSUE TITLE
Update an old email address on TISLab website for Matthew Brush

### ISSUE THREAD

**Issue by tursynay** [tis-lab/tislab.org#20]
Please update the email address for Matthew Brush from brushm@ohsu.edu to matt@tislab.org.

If one goes to tislab.org website and clicks on team (top right), then clicks on the icon for Matt, the email icon is set up for mailto:brushm@ohsu.edu, needs to be changed to matt@tislab.org.

Here is the page: https://tislab.org/members/matthew-brush.html where the incorrect email is listed.

**Comment by kshefchek** [comment]
closed with b5bbe771
