### ISSUE TITLE
Add contact person for each project.

### ISSUE THREAD

**Issue by jmcmurry** [tis-lab/tislab.org#31]
For each of the projects listed, link to the corresponding page of the person who is the main contact. https://tislab.org/research.html

- Monarch Intiative: Julie [also there's a typo in 'Initiative']
- Phenotypr: Julie
- CD2H: Sarah
- Biomedical Data Translator Program: Julie
- INCA Tools: Dan
- Undiagnosed Diseases Network (UDN): Julie
- National Cancer Institute Theasaurus (NCTt): Nicole
- OpenRIF: Robin
- Annotating the CRAFT Corpus: Nicole
- Web Taxology project: Marijane
- Open Insight: ?
- CTSAconnect: ?
- eagle-i Network: Julie
- Resource Identification Initiative: Nicole

**Comment by nicolevasilevsky** [comment]
done: https://tislab.org/research.html
