### ISSUE TITLE
cannot click on publications

### ISSUE THREAD

**Issue by nicolevasilevsky** [tis-lab/tislab.org#32]
I cannot click on the dropdown for published works

![image](https://user-images.githubusercontent.com/6722114/149210712-520db45f-8786-4bf8-832d-109c645f29c6.png)

**Comment by vincerubinetti** [comment]
That is a tooltip, not a menu item. It is meant to be "helper text" that explains what the link is/does.

**Comment by nicolevasilevsky** [comment]
Ah, I see. But this page doesn't show any published works. Is there a link to our publications somewhere?

**Comment by vincerubinetti** [comment]
I don't believe your old website had a list of published works, so I couldn't copy one over.

You can change the tooltip text on the page's frontmatter. Maybe you'd want to rename "Research" to "Projects", and make the tooltip something like "Cool things we've worked on".

**Comment by nicolevasilevsky** [comment]
I see, thanks @vincerubinetti! I appreciate your help!
