### ISSUE TITLE
add a page for tools / products

### ISSUE THREAD

**Issue by jmcmurry** [tis-lab/tislab.org#32]
Ontologies:
- HPO
- Uberon
- UPheno
- GENO
- MONDO
- Sepio

Data Tools and Algorithms:
- Dipper
- Biolink
- Owlsim
- Exomiser

Monarch web:
- Phenogrid
- Hippo
- Analyze Phenotypes
- Text mining

Curated associations
- Disease - phenotype
- Disease - gene

Evaluation tools:
- Reusable Data Licensing Rubric

**Comment by nicolevasilevsky** [comment]
@jmcmurry I am working on this
questions:
- Exomizer isn't an ontology, right? Should it go under Monarch web? (https://monarch-exomiser-web-dev.monarchinitiative.org/exomiser/)
- For text mining, is this the link I should include: https://monarchinitiative.org/annotate/text ?
- For the curation associations, can you share links for those, and any descriptive text you'd like to include

**Comment by nicolevasilevsky** [comment]
new page is here: https://tislab.org/tools.html

**Comment by TomConlin** [comment]
sepio?

**Comment by nicolevasilevsky** [comment]
@TomConlin I added sepio.
What link should I use for scigraph and owlsim??

**Comment by jmcmurry** [comment]
Sorry about that typo; updated categories above. This is good enough for now, but there are other things we could add, including peter's desktop tools and the ontology libraries.

**Comment by nicolevasilevsky** [comment]
@jmcmurry For the curation associations, can you share links for those, and any descriptive text you'd like to include?

**Comment by nicolevasilevsky** [comment]
@jmcmurry For text mining, is this the link I should include: https://monarchinitiative.org/annotate/text ?

**Comment by jmcmurry** [comment]
for now, yes, thanks

**Comment by nicolevasilevsky** [comment]
closing this ticket, the new page is here: https://tislab.org/tools.html

Please reopen or create a new ticket if you'd like additional info on this page
