### ISSUE TITLE
add concrete examples of our competencies

### ISSUE THREAD

**Issue by jpgourdine** [tis-lab/tislab.org#36]
Show the usefulness of our methods with concrete examples from people who cited our work:
Example: Phenotype driven approach for genetic diagnosis/variant prioritization with exomiser 
[Pubmed](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5049788/)
HPO: 0012125 (Prostate cancer) + 140 genomes from Japanese patients with Prostate cancer from 66 families--> Finding: new shared variants of BRCA2, HOXB13, and TRRAP deleterious HOXB13 variants

**Comment by nicolevasilevsky** [comment]
@jpgourdine how to you envision including this info on the website? can you be more specific?

**Comment by jpgourdine** [comment]
@nicolevasilevsky  it can be more simple than what I initially thought. We can just indicate some impactful references citing us because they used our tools/products [here](https://tislab.org/tools.html) I can help finding them,I think @jmcmurry has kept track of people who cited us. What do you think?

**Comment by nicolevasilevsky** [comment]
@jpgourdine sounds good, if you'd like to work on a list for this webpage, I can implement it when it is ready.

**Comment by monicacecilia** [comment]
will add publications page. :bowtie:
