### ISSUE TITLE
We have some TISLabbers missing on the team page

### ISSUE THREAD

**Issue by tursynay** [tis-lab/tislab.org#46]
These Tislabbers are not there: https://tislab.org/team/

- [ ] Kay
- [x] Anh
- [x] Sruthi

**Comment by nicolevasilevsky** [comment]
pinged Kay, Anh and Sruthi on Slack on 08/11/22

**Comment by nguyenanh3** [comment]
Hello Nicole,

I just sent you an email to your tislab address.

**Comment by nicolevasilevsky** [comment]
Got it, thanks @nguyenanh3!
