### ISSUE TITLE
Is B2DK something TISLab still does?

### ISSUE THREAD

**Issue by tursynay** [tis-lab/tislab.org#47]
We have this listed as something that TISLab offers in the education page:
https://tislab.org/education/#bd2k-open-educational-resources

**Comment by nicolevasilevsky** [comment]
Yes, these are open educational resources that are available. They are not actively being developed but they are still available, so I think it's okay to leave it as active/

**Comment by nicolevasilevsky** [comment]
I'll close this but feel free to reopen if further discussion is needed.
