### ISSUE TITLE
Move Our Research page from TISC to tislab.org

### ISSUE THREAD

**Issue by nicolevasilevsky** [tis-lab/tislab.org#59]
OUTDATED REQUEST 

~~Need:~~
~~- [ ]  name of all current research projects~~
~~- [ ]  description~~
~~- [ ]  grant #/source~~
~~- [ ]  who is working on the project~~
~~- [ ]  contact person~~

~~https://docs.google.com/spreadsheets/d/1UT96EsmTi5ooTPtQGRJYOZV9sLYWiqmb80DrN9f8bC0/edit#gid=0~~

**Comment by monicacecilia** [comment]
UPDATE: 
- [ ] Transfer information from https://agsci.oregonstate.edu/tisc/our-research to replace the contents of this page.

**Comment by monicacecilia** [comment]
Will assign @oneilsh when he joins the organization.

**Comment by diatomsRcool** [comment]
Done in #73
