### ISSUE TITLE
do we want a tislab twitter account?

### ISSUE THREAD

**Issue by nicolevasilevsky** [tis-lab/tislab.org#6]
or we could link to the Monarch twitter account on the bottom of the page (or just remove that link all together.

@mellybelly @jmcmurry

**Comment by jmcmurry** [comment]
I'm reluctant to have yet another twitter account to babysit; we can barely keep up with the ones we have, but let's park @ tislab and have it at least say follow the #tislab hashtag in the header.

**Comment by nicolevasilevsky** [comment]
@jmcmurry what you mean by 'let's park @ tislab'?

**Comment by nicolevasilevsky** [comment]
I created a twitter account, but couldn't get @tislab, it created it as @tislab1

**Comment by mellybelly** [comment]
hm don't love it, maybe #tislab is better for now as julie suggests

**Comment by nicolevasilevsky** [comment]
I agree, I don't love it either. I can take it down.
