### ISSUE TITLE
Migrate CAS About Us page

### ISSUE THREAD

**Issue by diatomsRcool** [tis-lab/tislab.org#70]
https://agsci.oregonstate.edu/tisc/about

**Comment by monicacecilia** [comment]
@diatomsRcool, @nicolevasilevsky had created a ticket a while back with a little 'nice to have' feature called 'poker chips' 
we can consider if we have time between now and Friday. See #61

**Comment by monicacecilia** [comment]
@diatomsRcool : #72 added a new Join Us page. 
Was this intended? 
Do we keep both? 
Get rid of the banner on the home page?

**Comment by diatomsRcool** [comment]
About Us and Join Us were intended to be two different pages

**Comment by monicacecilia** [comment]
Yes. Agreed. There are currently: 
- an About Us page at https://tislab.org/about.html
- a Join Us page at https://tislab.org/join.html
- and a Join Us banner on the home page at https://tislab.org/

Is this intended? ⬆️ 

---------

Secondly, Top Level menus are different on the Home Page compared to newly created pages such as _Join Us_ and _About Us_. 
- The Top Level menu items on the home page are: 
<img width="633" alt="Screen Shot 2021-03-02 at 2 53 32 PM" src="https://user-images.githubusercontent.com/1714621/109726179-1808a600-7b67-11eb-8144-a32ec1a78007.png">


- Top Level menu items on other pages are: 
<img width="482" alt="Screen Shot 2021-03-02 at 2 48 47 PM" src="https://user-images.githubusercontent.com/1714621/109725724-68333880-7b66-11eb-8e28-f9e897c7c99e.png">

----------
Lastly, @nicolevasilevsky and I am sorry I just now noticed this - the 'page title/name' that shows up on the browser tab now reads _'Research'_ (as expected) in the page describing our 'Research' - AND unexpectedly for the _About Us_ and _Join Us_ pages. See the screenshot below. 
<img width="1017" alt="Screen Shot 2021-03-02 at 2 50 38 PM" src="https://user-images.githubusercontent.com/1714621/109726086-f3acc980-7b66-11eb-8e37-a94e405fba99.png">

**Comment by monicacecilia** [comment]
Uh-oh. @diatomsRcool - just saw this. When the screen gets narrower... 😢 ... the text in the bottom half of the Home Page gets squished together. 

@oneilsh - maybe you can take a look here too? 

<img width="1027" alt="Screen Shot 2021-03-02 at 2 57 31 PM" src="https://user-images.githubusercontent.com/1714621/109726455-a0874680-7b67-11eb-9983-bb86663ca5c9.png">

**Comment by diatomsRcool** [comment]
Yes, I don't know how to make the screen narrowing stuff work. Someone else will have to do that.
The menus are still a cluster. Haven't gotten around to it. Pls fix if you like.
I have not done anything with Join Us page, so prob a lot of mess there.

**Comment by nicolevasilevsky** [comment]
> had created a ticket a while back with a little 'nice to have' feature called 'poker chips'
we can consider if we have time between now and Friday.

We need to know which project everyone works on. I won't have time to create the poker chips before Friday

**Comment by diatomsRcool** [comment]
In PR #74
