### ISSUE TITLE
Remove Twitter

### ISSUE THREAD

**Issue by diatomsRcool** [tis-lab/tislab.org#77]
We should remove twitter from whatever project don't have them anymore - and add linkedIn or whatever is replacing. Twitter should be removed from my profile.

**Comment by chrisroederucdenver** [comment]
Xwitter links that fail:
- GPE doesn't exist (GenoPhenoEnvo)
- N3C is suspended https://twitter.com/N3C 

Xwitter links that work:
- Monarch
- kidsfirstDRC
- Data2Health

**Comment by sagehrke** [comment]
Remove Twitter from Monarch. We are protesting that platform and are now on LinkedIn.

**Comment by chrisroederucdenver** [comment]
@sagehrke Can your provide a LinkedIn link for Monarch to add while we're here?

**Comment by sagehrke** [comment]
Yes! here is our LinkedIn: https://www.linkedin.com/company/the-monarch-initiative
I've also mentioned updating the social media we list for Monarch on #84 so there is a bit of overlap here.

**Comment by chrisroederucdenver** [comment]
@monicacecilia @diatomsRcool @mellybelly 
I see twitter accounts on your pages for monimunozto, diatomsrcool and ontowonka. Want I should remove them?

**Comment by chrisroederucdenver** [comment]
Twitter links removed with PR 102.
LinkedIn remains undone. It's not a mindless Saturday afternoon thing... I'll push this to #84.
