### ISSUE TITLE
update nav bar

### ISSUE THREAD

**Issue by nicolevasilevsky** [tis-lab/tislab.org#8]
@mellybelly @jmcmurry 

I don't think we need OCTRI and CGRB on the top nav bar on the website, I suggest we have links to other pages instead:

- [x] Projects (or should this say "Research"?)
- [ ] Publications (not sure the best way to capture this though - it could link to a PubMed query that searches for all the team member names? Or a Mendeley group? We are trying to sort this out for HPO and Monarch, right?)
- [x] Education - we have this on the [library site](http://www.ohsu.edu/xd/education/library/about/departments/ontology/projects/index.cfm), do we want this again?
- [x] News
- [x] Funding - Maybe this could go on the project page?
- [x] Contact

_Maybe:_
- Community involvement? (_just brainstorming here_) We could link to Force11, Galaxy, ISB, etc

**Comment by jmcmurry** [comment]
Re: publications we need this list from lots of places. We discussed Zotero on another thread; that may be appropriate here too. For now we could have a single central location for pubs and can link to the one.

**Comment by jmcmurry** [comment]
a list of projects is still a good idea; I wouldn't bill it as education per se.

**Comment by nicolevasilevsky** [comment]
a single location for pubs sounds great

**Comment by nicolevasilevsky** [comment]
@jmcmurry can you take a look at what I have so far? I can combine the education with the research tab if you prefer:
https://nicolevasilevsky.github.io/tislab.org/index.html

**Comment by jmcmurry** [comment]
This looks great. As you have them broken down makes sense; the edu materials are now much less project specific. There's a missing paren before CD2H and in general, I think we may want to have consistent structuring of acronym and spell out for all projects. Thanks :)

**Comment by nicolevasilevsky** [comment]
done for now.
Made a new ticket for pubs #13
