### ISSUE TITLE
Make TISLab Research page navigable and about the program not about just grants 

### ISSUE THREAD

**Issue by tursynay** [tis-lab/tislab.org#85]
From Melissa: I wonder if we could make the research more navigable too, as well as up to date. It focuses on each individual grant rather than our "programs

**Comment by sagehrke** [comment]
"The Monarch Initiative" section could very well be encompassing the main Monarch grant, Phenomics First, HPO, Exomiser, and DataWorks! prize as opposed to listing them all separately. Would need approval from Melissa/Moni for content.
