### ISSUE TITLE
Include links in TISLab website to TISLab relevant GitHub sites 

### ISSUE THREAD

**Issue by tursynay** [tis-lab/tislab.org#86]

**Comment by chrisroederucdenver** [comment]
CURRENT RESEARCH
- Monarch has, works
- P1 does not
- CLAD does not
- CGPE has, works
- BRIDGE does not
- Forums does not
- K1 does, works
- INCLUDE does not
- TRANSLATOR does, works
- CD2H does, works
- N3C does, works

PAST RESEARCH
- PNC for TEHR does not
- CCDH does, works
- UDN does not
- Phenotypr does not
- INCA tools does not
- N-Lighten does not
- NCIt does not?
- OpenRIF does not
- CRAFT does not
- Web Taxology does not
- Open Insight does not
- CTAR does not
- CTSAConnect does not
- eagle-i does not
- Resource Identification Initiative does not
- Biospecimen query does not

**Comment by tursynay** [comment]
Thanks, Chris
