### ISSUE TITLE
Add Human Phenotype Ontology?

### ISSUE THREAD

**Issue by sagehrke** [tis-lab/tislab.org#98]

**Comment by chrisroederucdenver** [comment]
Should we just lift that first paragraph and graphcis from
https://hpo.jax.org/app/ ?

**Comment by sagehrke** [comment]
@mellybelly do we want to have HPO called out on the TISLab Research page? Currently, we have Monarch and Phenomics First in their own callouts. Seems like a good idea to also add a specific call out to HPO. But, I'd like your opinion.

**Comment by sagehrke** [comment]
Also note, that HPO is now listed as a tool on the new Tools section here: https://tislab.org/tools/ so perhaps this ticket can be _closed as not planned_.
